# Generated by Django 5.0.1 on 2024-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Language_of_create',
            field=models.CharField(choices=[('django', 'Django'), ('djangorest', 'djangoRestFramework'), ('html', 'html&css'), ('next', 'nextJs'), ('php', 'Php')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='time_of_create',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
