# Generated by Django 5.0.1 on 2024-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
