# Generated by Django 5.0.1 on 2024-04-16 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
